apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:EOZ/xN8Zj9XI7gaKJIqxEPgGPRahIRistZ+S4aIpAgoWs86vaOjGqw==,iv:4eTToC6tsXzZeWhEjfeGVZJJxB9RR6a9cUatv9jo8KA=,tag:o/G8VA6KOzBCegxL6fhmTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV204OXZEWDNaNURKSnBF
        TjY4RnNieW95b0VudnA1dS9scmtJaEZsUVgwCnpxbms2ZzBpbytSMVRqMTNtMXNx
        YUtjRXBUUU9YdTAyTWo4R3J4R3k2aVEKLS0tIHluNWlBNmdLWVB0OGtnRlQ4QXpD
        dDUyT0tRUFFobXcvMDdacXVFME9JT00KDa5mDVJvT+0V1iqLhCNDNYeSO5/RFL7Y
        JLkUkz/ZA1AQ94XpLiasYY5Gf4Ad9R8iu/PiLM/DQWTZeJ20lGxZdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:34:19Z"
  mac: ENC[AES256_GCM,data:S2CBbBCg9bn8OORwnUAaEdngsF1ZKGnFMv/WpmgSnRGLoriSusYrQMUKV4HNbOKau9K73UKOd8ajx7fFXEXd/kH4hKh+XO6/723WdmH3oS1fsQYHSv2qJSuD7nla0WYeQWJ+PFjm4nszBBI5QvG23GAZ+PaH6eLB6kShluVeEHg=,iv:P8T25mZ5OPPCrfqTThv0Ytvga7qxD1S8onvPBadCq/s=,tag:IX8nxn7h5ylhkTeX5IT8ag==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
