# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pjx0Xd/HTWbxEj+fZcHChoG8fdNeISaRe1jRr4NIOGbK9mBzNcDp2w==,iv:T1a4g//mxi3gbFlTnWK4JcTNUyOAaiNFuLmCmJcs0Ac=,tag:xxfGGN9iAydfaTtWK301fw==,type:str]
sops:
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY2IvT3R0NVZjWHFubkJV
        VVllSTdkSTRwTWtOQmVKUkdOTVRPSzU1Y1RRCnhRZHdjdGVHUXBXSFQzREZ0YlRw
        STV3VU9scXZtUEV3dTdHQmdNQWgwdkUKLS0tIFY4V3libWRJeng2aEVBaHM5eDU2
        S0MwRHZwRXQ0cy9kcUpvOTNzaXJpU0EKQ+VTzq2HrJxU6Q+U5uqEH7VvzLmtrYUr
        gf13BW8T8F775a4LbqK4J7N3Kqx0QQsSsgpB4uzlHkWceyF/15RKmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-03T19:34:54Z"
  mac: ENC[AES256_GCM,data:t7YK1f+7Hqtr5jAQDC1wn0zn93HHNeMVb61wJmVncfNLacPbspmGvGDetkU6mMDFpxuJFcQy273dHWDcukw7znHqxWYyLOVLazXNhOtmI1m6Jf3Aux/GxqHdnqARiDFcnaZstnvyupGC7XYRXvUi60KwP0aNHWYzMZA7/JOJyqI=,iv:1Jt+gkOzGIL/XFdQQRDx2KMSW8n/TGKjdSzAw5lEu00=,tag:FPXgbhTHkV0uzM9XzZvGSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
