apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UaKtaBBRe6ASVksXx2IryTU+Y29AI3wJpFFFrVFgJP6YAB2kPuRAyg==,iv:o83M4ecCfSR71Jyf52y75PfvTg8dK3LCsUPi3w8P2DI=,tag:7Hnz6psB5EJJt/TPesw9/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZmpxcmRGcXhjWDhrUjlF
        eVo4b2RGbE1LUlhwUmc3c2RnN25UTWVOL2dvClZlb1ZpNlNKRDMzYkFpRHFMdFQ2
        VzlUd29WajdmcnZ3L3lZdDI1S0RDRmcKLS0tIGJtQ0JZU0tCVFFQSGt0dzNzZTI3
        MXpxMmU1dmdBUmhzdHpKRER6OEd1M2MK3e5LxpE8VNn1tNCL3g0wSg963XxuGabE
        F9C5T4VA16e3IRdlsYFOun8mpkOJ84W8uVEfNfSil3JcUR8FkMzsfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T18:36:44Z"
  mac: ENC[AES256_GCM,data://ZTurXTPSP3sLhPKlpGSaHAfaNhWsiBNjIGA5cl3Kkap3pzMqr1//k/FutfPFE7Ya6jMiShORXaYxqcAyPnNTSQBBCpLWJmGfyuUvJpFN5HatD0j1UZnw6h1/pkZZ+ZBn7r6QxeUxRJgpVIQRoneP2NyEj71zfyHI8BLXCtdJU=,iv:45wxyFc7N5HtTzs7zCBlQqNaC0PZDgexHEwVgl/b2n8=,tag:nFbQV6DmFToK6q61+TBfHw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
