apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kvtcUIF1n/QyUVIR7K95,iv:owMOWEHJ+s3/iOTCKCllpSGt/Y+zLVL20inMsVX4ANw=,tag:jaOBWiadsnN1GgZvYZP6pA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISXJkNnBDbVQ4Wnltdldr
        RUM3U3NGUGs5RXNLaExUdjJZNG5Ld0loRlg4ClpDV1AvTHJpNk5nWnRRSmUrU0Ey
        djBqN1B4a1hLRHVuallaN2pFdzBrYzgKLS0tIGd3NzVnNVhJWTZZZjg4Z0dubTZV
        OFZuOFlONE5xSEtFWFJtc3FNRnh1aWsK1D7F5/KstlGa7nxcRj+aEOyWsXQze4He
        nbCP1qr0yRsTB/As+KoHuL4ianEmw6tOoxmcvHE587cAKOsD0YSQPA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:34:19Z"
  mac: ENC[AES256_GCM,data:W3vDfhhaPj8VVJtqn3CLlT94GY1cTHejSHH7TD78JPUZ/MW80u420Pk5M4VqUtjXB1lpyNBMI8zs62kMTED27PcLawFvvdnonwQrjRUbSQQMOtM7mVKp4EWZcY2RS0CPL3INi7Xt4ZiHJwkyjNg+ZsKgo+WOF1+M5/l4WPermEI=,iv:38Q4dWMoQfd0Ngxg61K+HlRnbZpEdZ26VRYf94Z7nZM=,tag:Dnbn20X5dQqHj64jSD7MUw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
