apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KnP1p0DA8iAD2XEim+Qg,iv:MSSwRgbpsBmfggwN8e+SeDMmBvhEQIo/pn8IxEOrV9I=,tag:LgMnuQAO3xKO5p++CWAYqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNzF6V29VWC9NdEZJaTF3
        ZXBsN0MwdUc4b2t0T1QxZHNBaHN1cWtzV0F3CnZkZEVDcFNhdmRtaTlSd3JsNTdj
        b3JJMFM2SUdzbVpHb1NGakZiV1Y3cWMKLS0tIE91b3U3c2JaR0lnSHE1dDFTd3Jz
        OFFiM3NsM1M4WnFvdXlhWFJxdXZwMkUKI+e/CE7AVfwBtLyZOeJ6gcJv0NvCs9IX
        rmtotiZ16U661Kh+yMmbOI20izYVi/zQ/sDgpnNg09qp8OZE2/g42g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T18:36:44Z"
  mac: ENC[AES256_GCM,data:MonDiCJpSefsC5SKDrq56kIU7GVj+cCj13ErHuDJHNrJaA1pSPIM0+7UTKiqSUJtMvJJkeUBhC5DYCO+UekPBwXyNvFIIFZbGu6/TvUWSjERq/C/g4u32jlgZvk0asLzRyfSmP9aYfYtN/d5XXaDY7HrmYeNh6OWUTAOk4HMFlw=,iv:1O1o8uyuyfETUZlkcZvM9CcmRp5LaKKS5WnEXXjVzoE=,tag:Lmh144F3S51PxQd2yUFm7w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
