apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:T8Rvw12bxsAIbZAUVuUNYIf8aMa66ZqPccgfhP4r+G8=,iv:DSreeZZa2cYnOqi6Rxfm9mVt+FF92IGJVPXN9CecyIE=,tag:nOG8tn7fD2UfiPJrNly6uw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUS9rVjIrdVdEeE9sUklE
        TCtzSHQySVhDOVAreXQ3MVFycDUzUm5EY21JCkRudEZLS2puemZtOGJkZ0ZhT1k0
        VkNYYm9OOEdOVjk0aSttN2hzVUd1Z2sKLS0tIGtYejNOSTNWaTF3Y200L0JHUkNU
        Z2FjS3FnOWxaRzQxRkRNYjM4RituUDgKX8WMqD9EQjxG+adZnKu18T3rEi+utOmy
        hKzh2PKBBPSr8HkT+qSpDK4AyZXbv0Y/1dtGv3OXhIINLfzQzcnpow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:34:19Z"
  mac: ENC[AES256_GCM,data:TvSvBM3t29D1i4FS5cNpWHkSXybhBsUDCzveDX9KJhW929pP3ENrRSdL2CQZ9R+E6tYr+xcArBWkkLEkT9cvLmcPJgIF33i7UybvCSiQvSbwQCxDqfN6qwSyWeYXuNAbnmfhoCRbFYeSrmls9RvuaaymbByKxYhS7ak5ZGg2ris=,iv:lwS0n1uSYAdrapkLIjPDXlGpYKcRP1yTPAIoH1n3aqA=,tag:h1acF5fAbdtI/ZlObo5i8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
