apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:LCuDxlWgEBlSzkNn1ldYNwicDrU0ez2eDyWRcKQVAcw=,iv:bYH5q0IANxIGU3aK9gOAyYUHzAETGfcIsGIyne9xxzk=,tag:XSbowLEyQbbRlqAeyFJL5Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZExjc3lqa2hLOTZ4T0RS
        YWpKNWZNSDVKZENaRVhQcDJkSUV4d1diaVZFClRHNktPdVBiRjhYVW16V3gxYllX
        eXZWL0dITUFMOEoxcjhvbGFCQThrNzAKLS0tIFRGdGZOSzJaYjB6SFpyZHlDZGF6
        cFQ4MjZJZGtYclNGLzFzZFRwdVFiTmsK+xfHBvPpSQ5FbNAvFJmGSvSMwLRS/4vF
        nCwbW9UvqPAk69KkZK7TiWCPrV8xCqdEJVNYccErSTM81ulMbc1nkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T18:36:44Z"
  mac: ENC[AES256_GCM,data:pWj+AYgCxFTmdXP79wyxwlQXeHGZqddqkP4YS6aRlZ0jJZHJMcBFHyhvokKE9SwwSTZHWzNpGvKMlm73KwYa1RVOu1Up6w4nY74k5HrjDg5N3/O1Bxjelrxp/FFMlIZL0nUsAUnSz2FBAw0heU52ARiz1hAPOBYCszwnc49ZAdM=,iv:gLnvXfKHQlp6T01+ECGCyBr3BKu3MqISuOO97IW0YHg=,tag:6tctiiAeIjzmop+3lPIVPg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
