# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:i246pPwuCOKsGkbByvYDaMfjR61L4Iq7LF1TbTuOFCY=,iv:gRKWj6kiVQckUDuDObhUHfYw9xudpYJVun21hRiUH+A=,tag:Nf7QaPh7s0PnW9uZ32332Q==,type:str]
sops:
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeGNnVWpOaDFBZnhaQzEw
        V3FTZWV1clVvZTRBakVQeDJpMzQxRms3a2xvCkU2dWJ1Z0dlcjJJdXd3U0FrT3NP
        S3R2emgwMElwTEFiL0dPMUxMaGU3WUkKLS0tIGgwcUdHRmN6ODhuNVVrdDJTQlMw
        dy9BUmhMK3lwQ01EUU5SNjhiOHBLc28Kw7VtWc5Y51IowdQfRuAJ29tvHr/sixsF
        BX7vhMrsfP2f4h4LzSNnr2zTu4a4ye/qqe+cBclwx/AWWkBxf4Tj5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-03T19:34:54Z"
  mac: ENC[AES256_GCM,data:lOHJskkplZNukzs/Lgw6YwO/9JW9BcMJuRE6dqLocXgH9Ta/PDsIkxJU8jy4PTevZPwWD+9yakdYGArrI3Nx24OXyuB2C5LWHb2LckrN3jir2EfcuQv4LC+xi7aDbTA8kQXy7BIfgcPZ35TDs2gnPz5ENpKdRq37/y2CDb6aeC8=,iv:D8VbFGobvELjES8/aIKqUB8xIdpiqqVNsrTZQf8rDw0=,tag:eTeWv0x/Nq+b4h1u92b3fA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
