apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6Cy+ijA8w6javg59bAMVhFk5vMD+rTh1PF5XzUxcXYwIICSNrz0YKZipuKe0An8oRQWd7ZgX4N/lNg59KsaHU6OD4LW/igF2QKwAclpMTUcK8bbujdPKfDhinJnUSnB9rd+rkS2JIeWMB+No0baEiG7Z096phZ4oTYEjYfRc7RODfqCYFTdYyghiyheCs/A8k4zg4Vw32BIsz0nDefwaEAc7T8uaszzoKPL0DdAWifR9M1Uz,iv:IhPjbzu8nOdgRi1GAKFQC04Va6OVqxamgVrjyTepLSc=,tag:tJIKrP1QUPkvpnyQ38/5sw==,type:str]
sops:
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUjYrbnFuV0tOWFVwTW56
        VUNSYTZsQnkxU2ltYTRVTXRMVi9PbmNSK0dNCjZVTWJsWkxrcExlVzMyalBvNDZE
        UlpZUTBWY3VwZzFTS3dMd3pWSThOaXMKLS0tIHh1SkYzYTZGMXEyY2RVYUQ5UlNZ
        SVpXcE11VU45N084T1pGcmx0RWVTSGcKy5KRTxIdezctLcHoabLxq310bDGbEYb+
        BzV7+11chMln59Iwz/UqwUscjx5DAvkSkKCI8HVm81IbhdA9Mw+b9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-25T08:44:32Z"
  mac: ENC[AES256_GCM,data:Z4LP2NHCQoqUlznEBhgeWVDYSwzZRiP9PUo6d0Af84AljeQ7YNFJ14wW5vqMjZP6NeiXx05VhK0wxl/UYB8954ekWzFGabpIpPhN/lfO8rK4CrZ4kOe9aO1gtlBzbzEBPbNIh9EoQvQOBms1hs0N4AFaTKWNhdgzEt3Qm3Uowh8=,iv:Wu52r00KolJ5sAB73GPV3kPooQivnQqaElSF4YrJ2EY=,tag:LeLgL1+H3OPaVu9ly2bYSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
