# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:IApzgJsPCq7gPZRz14zUtdsMo96IuPVffwtvh+y8VNX7jryMZ3RQLZGpWT/nqIDTWKbMM0/t4nU1VZbcwsR/A6bNszlSjN4RW3+VMxfHb6ILVliZbAmXg/bRkRVBbT4JUG7bIWeKbkvoeZ4PZMqo6RexPDqnA+l8qO+Ctjb1Ncr4oyp/0WVTO6Bx/tS5KP8Gf0i+me9NGTZ0I9Oo5M3Ovf6q4gp1zq1jWNqrKHOwXZiziC7n,iv:3XVRzEUP72w/8JBW8TeM2wdA7rRSje9qz02hvcvJ4LE=,tag:LTiR7itRWSsos7OUZ1P7UA==,type:str]
sops:
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WFBrdTcwV3ZtVmdCWk51
        TmpnS3J5QWxKcXNvL3VZZFFaVk1YWENONTFzCkNNRGtpbjhPYXNIZ1ZWOHpiZ0Rt
        MlMvT2lTaXN1aFduSzZIbmJpdjgyYUkKLS0tIHFuVXJXRXRPSEQwZVMwWEFTdVhh
        QVB0R09IL0xrcDVJMndobGJMRS9qQmsKGEAD/nKAKh71BuiN75R3wUACPlBXkktp
        jbg5jj7V/kkzUB3DI8JnaA+h8AuV8jqMY6yJsY/lwsbzlI5hWy3pLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-03T19:34:54Z"
  mac: ENC[AES256_GCM,data:Fn2d4ygr+4+11HLdQPnZ2FNFehRnSfII4LzJ6vk2+N/koTDuIiOXO0H+TaP9esLFXTpZSFVbHdBx5B1dRDjf5DRNpQNBtuBmNhBfJdlZ9NQG9896gRR41U2XVDD/QjEA+3eHRcYRb/jL1nRRa4N4w+cBK4WRMPXBxvVqwar83go=,iv:x41j+2lmuS67Epkl7MFnPAS8vf0VbVmD612H7iTNg+A=,tag:OvWttuuus2hx7W1cjDzp1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
