apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:MwdN3yhlDOudRXMW3Z1FS6vfhg5ezNjX+Z1NlSxh0vPtjbtAMecXemvRr6wEtFsgiSsfXAv7jo489bI5//saZmo5tDU/20SG6PaFfc8AmKJxIZyXde8n+lnOfcCcYRx6hF+pRuUWlB5GBWjSMlLWBbp+vbTxI6b38aVz+kdgqYIz/DY4y2CnVpznmOX1sisZoERXfMDP8zmXWsaQfSRyszuDPyachKoOpGwhty0kNUTsnvhQ,iv:zajDHyPnAscirvbEY2gTomoQq2PAOH6GucX6ZSZhrXY=,tag:NNcdUZQHdAha4PDKOHMiFQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM0F4aU9lb2s5S3RjcVZK
        ZThpZ3Y5eHl0WS9hTjRZYjUvUVRlbFE5czBZCjZhNHZ4QUZhdysrb1I2WkdGRkJi
        bUxvZ0s1ZGJ4aHIySkF3TlVCZUxaUUUKLS0tIFJLUmNkYk1ZZnBnTnlQOTRCMUJk
        dkFnWVNoUFBWREQ2NVZmODI5Rld3NTQKa3Iu+D1xgNkuPIKTSIn1Pb8pkEuOxmbM
        2NWlxU6lLC28ES2bu7rIRJD6JV15gXVoAmKeV9bcyikUO7IkPwuQtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:34:19Z"
  mac: ENC[AES256_GCM,data:/P7aaHSg2nXt6tXtZryHfKTSr6Dt9y3/t3Wb8oKNuDfzZ3TDHpJICN+rw+Uz4Xi921TXxrW9wV2FPkP6GtQVQVotIJ7MM2/O+SGG2PT/EZkRNA8CQVbG+47/TzNH6dnnzqOgjXWsGWByHdAqZYJVBIX2IdCw+LXa20qPoKA9eJ0=,iv:CZwt9OGEbww3cQD5hcX3a2MEJhorGyRTcsBrfFjyo/A=,tag:UKLSQDIAewgCk+57J5qt9Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
