apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:aqbbxgZzVE8P8SrBaMzB98IJRAEDcR8GtZUQNngLJOwPm84nsZkD/ttwuTbfb4dm/0hGpAO1D4j7yTrzDnUkiCLi7KLcjmonEsxqnZlY9/hd8Ke4eqjw3+s91NXwGgYgJaHewSfQwXG26LWwjFu6yJ6rObA7ZbxF456XCxDeNdZKuJyEGUNC+rDQfm39uLHPRSGPiVUgcwloQVoSyb0sPxdtLHCXhBMaYfa38NQecghqnecs,iv:hbWtllIB9aR49Snfe6yLE+z//gPxUFrQ16AjxHRS7Y8=,tag:XteNqrlvWNGi39+zljYt+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bUtEVGVIVGNSKytPNHFl
        SzZlUzRsZzVIZW1HZXp6T3VQTzhBRHlab1V3CndmLzNxWkZ3ajVYSVNlNVlQMGpy
        Ynh0Ti9aRWw1eHBQOEt2RUEyOXhpd0kKLS0tIEZkMDllNVNrM2hFVEJjc2pqSWJV
        cWEyVGIyS1ZHc3AvSTF1WG9tbGYxLzAKEWv1q1t3mpkB+HZTqeyOSeD4FKDv4f1t
        ifhZO8mmmO5d/wuVaz+zCHDysWANwD5nfPbVJ1QS4WEt+6tECHIrWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T18:36:44Z"
  mac: ENC[AES256_GCM,data:lJlOcSd1Nu3cxYo8vkibOYPC0d00Gnfsp0quKxcDmvfBNEbNKcnm3dsZfbcVbszadS8y351woHCWUGBApBKjCmwdqD4J9Ta2ErJJFO6N3VhOQEkY4SV2uYJP/UJrtL3wekM3Y2etCMhW1MkEuRuLTkEGWmYFdmp3R898saofoGs=,iv:VtP1ahZBuisQNYgbZXMtcDrMscQqkXjA1nNyzFBW90M=,tag:DlffMB3efZX/Ssw8Q1oQxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
