apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:XhzNlUI4uzMfqfk//QIze1ccjEQ1orJOeklIhLvcPoOdG5HDAS4KiQ==,iv:ghgvhNvvD6DoVAuztp+OFKuVM8ZTLAcaULm3gNgeeW0=,tag:NE99ygo4tNxrBnpiPaZucw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QWdPYVBRRGMrb3o2TTBq
        ejVYQXJXcDJCaFNUZlptcndBMlJMT1plaTNrClVCU1M4b3lQODlvWEJueHhreVVT
        M3Q2VTVCQmxwTzJDQW54enczcWhOT1kKLS0tIFVwNVZaUjlMNEhRQWhMY3hzQ3Ju
        bzZSRUgremx5UndvZmFUd2lCYWpUTjQKqNa8XVEQ3QF10EI18KgzF5y8VZfZFi/k
        M7apLcdNrrr24smDPCIUTQaxjEN2igCII6ZnVl4uMrITaSr8KCkJvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T18:36:44Z"
  mac: ENC[AES256_GCM,data:nNnYE87JXCKuwTCZSgX1Jo8r4V+vM2FqklVQtDjP4B27sriyPqb/tiIgAhOZhs+47f0ZIxu+Yt6dSilTG9sWlXOWN733nYzfLNzuNu6D44ku4uuhM17qRmEuzMtAOiPZIvV8TGwvHbvspgiAOt8tVTmuq4Zi7FMrndC7Ds8VoWg=,iv:sgK8VXvqD8/YE1uMfgccaIrBQZp4T0IO3OvSnAiziAM=,tag:gQrOBxEaXsWDv6wRZAkIHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
