# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:00iC9UnBQx+vDHSZmJdlAxS8jYk+vk+cpgyKxflj/opdG5oiJBwvrQ==,iv:eOIpzqHN2YhxTuXz9NoT3WYAvpZxzVQhDYyUhXZEtn4=,tag:cbLMBnZu3x97izv4sFf0RA==,type:str]
sops:
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaU02YWtBMFg1bVZXa1RC
        dHkwZFFycnRWWm8vOHF6THFCZllsTWNLdlVRCk9WTmx0OFRFdEtRUUVlbjl5WGFL
        Y0ZSYUh2Wm9sRk5FajdvMFNQR1F1VlUKLS0tIGZ0VXpzN3B0OXIrUHZDUEtDT1NS
        SVBBVWZRZDB4Qi8zUUtpdHdSWjRDRzQKf6mxTHiIxkjlZVcEvr6ehUl1E8jeKAe3
        eNnV9acU/Zwj7zVtALRs0/HJpW647Nddr0+5+F6oU5lDjp8cDh68TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-03T19:34:54Z"
  mac: ENC[AES256_GCM,data:QGXSau3mF5uv6lpQQoCCkifptxEQvlYDixkGgj+yPlmCW41oM0EIknSeWhN3pD74HZ0vdH9aviW7n01b//I/Y6ZpuJEDgm/TMtLe42v4aKZfSe/qKe5ScinY3kmlhO86Ca0+K8qG59Kb8TOq/HfW+pQhwwJP1U/5MrnbcUg6P2M=,iv:3GFX2mRTagZ60Yu0UThQxicSakxn7hhDMAP19DkLGj4=,tag:9mSSTZi+BSgSQz1Q8NX5zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
