apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YfKSU3kmz4jeW5PxnixsQeTMXvW/Gw1gAwH9/KarXL0ukvxebqRwMQ==,iv:i00nSg4AE1ToaZMNMdqXwa4CN5hFhfydJHjKitqbdII=,tag:bA8/xxJyAoIpcNWGBmPQqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOXl1OVp1NHRGeXJVL1FB
        aTZNNEpEWlFoVmFxTXNRZ0JVby95ek44NVE0CnVyWUV1Z2VDL1I0YjkzWXYrUFpW
        L0ZwQWdmZEs4TWxvUFRjZXBOa0dTY3MKLS0tIFdUcnlVRXJWVWVWa25rUkw3Q0Z0
        ZUFaQ1BuQm9Wc2xCaXNxNEJ3VkdpemsKaqwe6ERAS6ZO+R3MvQ/vm3JXsjApy/RC
        6rs2HERhvTzN+QavRiWL8uxlrQ6BvzOuZkNy/v8TjV/Db4w3jwerGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T19:34:19Z"
  mac: ENC[AES256_GCM,data:L1rB5ue3CHQNM1fUBB6rfGTNZp2aU/UCW+JX4dWKAKC/oB5KPJCU+FWigAsKGdOHqG+H8URr2Hn21GMlzqlWH2xfqi7ekF+tZunOBs/fvKpNJBz/mz3TK052tLGQpRcGdv74TkcBdvoDI3Q7PgZPdXt8p+4DjYJBzsLkfwkFGF4=,iv:3IrRJNc9RncSHCMjzvIzn+wkl4cGNBjPb2Fb7HV6dT8=,tag:WLpuUkzvYjmbTMnIEIBSfg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
