apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ulNzuI96kYl67WxmMOwH,iv:lAY87VsExkYKEyeFt908lFOVkQJgogkCORBh+Oww/vY=,tag:c7NA70/TZ2B+wb3XpZvvBQ==,type:str]
sops:
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UG9Qb0hRMHVwTnNRSzR0
        M2lCeFg4WFhjQWh1Mm10TW5WQTVvRERNeUVzClp6YXhOa09RTjZQNGRFUEw0UDlm
        Q0daTXByRTh1R2VNRUJQS3QvOXY0ancKLS0tIFpaZWNSeEMvcG83akM3bURJUzlw
        WUVtdXQvdXdQMDZrV2wrb1lXM2Y4eFEKeXPSeee0/uJ+aB1yOzT+pbS6PXknvikO
        KY1zB2+zC6E5VZ18VMZY+oUj9j4FUQmWqOrbRM6GAXrGTf4ZmABTMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-03T19:34:54Z"
  mac: ENC[AES256_GCM,data:6+riaEmH/ngRVew1vDDMXS4p9dUYQmC78DFHChdop0j6uqNQGYl1wyXRTMS/u/Ur+G4u1mXs8fDfMlWNsV24ghXZ8ZLVn9/pmQvV4lQKRt2EYx5mzQv0Nbx0sk9oruo9LKDk6V6L633K7zJB5wvnETugCyFG3SKUC8TJ0atKZ/M=,iv:aRoco+j75h27hNz6ZHeaGRtywQbx8RQL/Osbd0SYn20=,tag:6XXeWr+gwyN5gMTcCTamjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
